name: insanichess_engine
description: Insanichess evaluation engine
version: 0.1.0
homepage: https://github.com/stelynx/insanichess
repository: https://github.com/stelynx/insanichess/tree/master/packages/insanichess_engine

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  insanichess: ^0.0.2

dev_dependencies:
  lints: ^1.0.0
