name: insanichess_sdk
description: Insanichess SDK meant to be used by client and server applications
version: 0.1.8
homepage: https://github.com/stelynx/insanichess
repository: https://github.com/stelynx/insanichess/tree/master/packages/insanichess_engine

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  insanichess: ^0.1.6
  # insanichess:
  # path: ../insanichess

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
