name: insanichess
description: Game logic and rules for Insanichess game
version: 0.0.2
homepage: https://github.com/stelynx/insanichess
repository: https://github.com/stelynx/insanichess/tree/master/packages/insanichess

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
