name: insanichess
description: Game logic and rules for Insanichess game
version: 0.2.0
homepage: https://github.com/stelynx/insanichess
repository: https://github.com/stelynx/insanichess/tree/master/packages/insanichess

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:

dev_dependencies:
  flutter_lints: ^1.0.0
  test: ^1.20.1
