name: insanichess_app
description: Insanichess app
publish_to: "none"
version: 0.0.0+2

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.0.0
  flutter_svg: ^1.0.0
  insanichess_sdk:
    path: ../packages/insanichess_sdk
  localstorage: ^4.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  assets:
    - assets/images/chess_pieces/
