name: insanichess_server
description: Implementation of Insanichess server.
version: 1.1.0
publish_to: "none"
homepage: https://github.com/stelynx/insanichess
repository: https://github.com/stelynx/insanichess/tree/master/server

environment:
  sdk: ">=2.14.4 <3.0.0"

dependencies:
  dart_jsonwebtoken: ^2.4.0
  dbcrypt: ^2.0.0
  insanichess_sdk:
    path: ../packages/insanichess_sdk
  pausable_timer: ^1.0.0+3
  postgres: ^2.4.3
  uuid: ^3.0.5

dev_dependencies:
  lints: ^1.0.0
