name: "[insanichess] Lint & Test"

on:
  push:
    paths:
      - "packages/insanichess/**"

jobs:
  build:
    name: Lint and Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"
      - uses: stelynx/dart-full-coverage@v1.0.5
        with:
          package: insanichess
          use_git_root: false
          main_dir: packages/insanichess
      - run: |
          cd packages/insanichess
          flutter pub get
          flutter analyze
          flutter test --coverage .
